stages:
  - test

test-frontend:
  stage: test
  image: node:20-alpine
  script:
    - apk add curl
    - npm install
    - npm run build
    - npm run start &
    - sleep 10
    - curl http://localhost:3000/auth/login | grep "eCrypt"